services:
  bambubot:
    container_name: bambubot
    image: hugo4715/bambubot:1.0.0
    build: .
    volumes:
      - "${DATA_PATH:-./data}:/data"
    environment:
      PYTHONUNBUFFERED: 1
      TOKEN: "${TOKEN}"