services:
  bambubot:
    container_name: bambubot
    image: hugo4715/bambubot:1.0.0
    build: .
    volumes:
      - ./path-to-data:/data
    environment:
      PYTHONUNBUFFERED: 1
      TOKEN: "your-token"